### ISSUE TITLE
Install on Python 3 doesn't work

### ISSUE THREAD

**Issue by darkyelox** [feluxe/sty#1]
when i install and import this library in my python 3 script i gets the error:

```
Traceback (most recent call last):
  File "install_modules_in_project.py", line 24, in <module>
    from sty import fg, bg, rs
  File "/usr/local/lib/python3.5/dist-packages/sty/__init__.py", line 3, in <module>
    from sty.register import ef, fg, bg, rs
  File "/usr/local/lib/python3.5/dist-packages/sty/register/__init__.py", line 1, in <module>
    from sty import renderer, primitive
  File "/usr/local/lib/python3.5/dist-packages/sty/renderer/__init__.py", line 19
    return f'\x1b[38;2;{str(rgb[0])};{str(rgb[1])};{str(rgb[2])}m'
                                                                 ^
SyntaxError: invalid syntax
```

**Comment by feluxe** [comment]
Thanks for your reply! Sty requires Python `>= 3.6` to work, sorry. I'll put a notice in READEME.md.

**Comment by feluxe** [comment]
@darkyelox Sty now supports `Python 3.5`.

**Comment by Ra-Na** [comment]
It does not work with python 3.5 due to some syntax error in primitives.py, line 38, where `renderer:` is not accepted. It works on pyrhon 3.7 though.

**Comment by NeoBoy** [comment]
Gives "Invalid Syntax" error on import in Python 3.5
rendered: str = ''
            ^
SyntaxError: invalid syntax

**Comment by feluxe** [comment]
@NeoBoy The version number was out of date. Sorry. Sty requires `3.6`. I updated the docs.
