### ISSUE TITLE
Missing effect 

### ISSUE THREAD

**Issue by Lazloo** [feluxe/sty#24]
Hey,

I tried the test example on my windows 10 machine. However, the results look like in the image: only the red-foreground option and the blue-background option show an effect.

Can somebody help?

![grafik](https://user-images.githubusercontent.com/10186284/65882196-e77e7480-e394-11e9-9e6c-da83a2e82861.png)

**Comment by feluxe** [comment]
Thanks for your feedback!

Unfortunately, the Windows default terminal is somewhat dated and doesn't support RGB-colors, 8-bit-colors and effects like *bold*, *italic*, etc.. There is nothing we can do about it. Fortunately microsoft is currently working on a [new default terminal](https://github.com/microsoft/terminal) for Windows, which will likely fill the gap.

In the mean time I suggest Windows users to use [cmder](https://github.com/cmderdev/cmder), which works well with `sty`.

I'll update the *known issues* section in the docs for `cmd`.
