### ISSUE TITLE
Release please :)

### ISSUE THREAD

**Issue by mar10** [feluxe/sty#27]
Hi,

currently it seems that we have to install with `--pre` or add `allow_prereleases = true` to Pipfile if we bundle your library, which is a thing I generally try to avoid.

Since you are in beta for 2.5 years now, it may be about time for a release?  
I don't see stoppers in the issue tracker, and bumping the major version later if you need to implement breaking changes later is no big deal either.

Thanks
Martin

**Comment by johanhenriksson** [comment]
Any updates on a proper release? Using this for [cowait](https://github.com/backtick-se/cowait), but I'd really like to avoid depending on beta releases. I will most likely have to replace it unless this can be resolved soon :/

**Comment by feluxe** [comment]
Sorry for the slow response. I started a new job this year and was stuffed with work..
There are (minor) breaking changes planned for v1.0 (see [new grey palette](https://github.com/feluxe/sty/issues/10)) and a [new resetter](https://github.com/feluxe/sty/issues/23), which I want to think through carefully.. I'd love to make a release over the christmas holidays :crossed_fingers:

**Comment by feluxe** [comment]
I released `1.0.0-rc.0` which means version `1.0.0` is now feature complete. I'll keep the `rc.0` pre-release flag for a couple of month, to see if any bugs pop up for the newly added features. As soon as I can confirm that it's stable, I'll remove the pre-release flag and realase `1.0.0`.

**Comment by feluxe** [comment]
The "release candidate" phase is over and `v1.0.0` (stable) was released. 

Resolved with e6dabaab23d90e6092961e237396a11037c1e335
