### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by mar10** [feluxe/sty#28]
I know it is probably too late for this specific feature request, but I wanted to give a friendly feed back anyway:

Assuming that *sty* is a library that may be used by tool-builders, a dependncy on Python 3.6+ imposes this restriction to those tools as well.   
Given that [Python 3.5 has an EOL of 2020-09-13](https://devguide.python.org/#status-of-python-branches) and will probably remain in the wild a bit longer, this makes it harder to to use *sty* to create a tool that covers all living environments.  
I fixed it by wrapping *sty* with a no-op fallback in this case.  

I assume that 3.6 was required in order to use variable annotations, which is a cool feature *internally*.  
However in my opinion it would have been be a better option to have a `sty v1.x` that supports Python 3.5..3.8 and then drop 3.5 support with `sty v2.x`.

As I said, may be too late to change this now, but you might consider this in the future?

N.B.  
I find the [Sty requires Python >= 3.6](https://sty.mewo.dev/intro/requirements.html) a bit hidden, it would be nice to have this more prominent on the front page.  
And maybe add the trove classifiers to setup.py
```
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
```

**Comment by feluxe** [comment]
I dropped 3.5 (early on before sty was used much by others) because 3.6 had much better typing support, which I really think is worth it. And now that 3.5 is EOL I'll rather stick with 3.6 and keep the typing.

`>=3.6` is the version range which I decided to maintain indefinitely. 

> I find the Sty requires Python >= 3.6 a bit hidden, it would be nice to have this more prominent on the front page.
And maybe add the trove classifiers to setup.py
>
>  Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8

Thanks for this. I'll defninatly add it to `setup.py` :-)
