### ISSUE TITLE
Bold reset not working

### ISSUE THREAD

**Issue by clozach** [feluxe/sty#3]
As shown below, rs.bold doesn't seem to be working.

![image](https://user-images.githubusercontent.com/124952/38168614-35317ea0-3506-11e8-9331-fa4248a4d146.png)

**Comment by feluxe** [comment]
Thanks for reporting!

Could you try this:

    print(fg.red + ef.bold + 'bold-red' + rs.faint + 'unbold-still-red' + fg.rs)

If it unbolds the text without resetting the color, a solution to this might be merging `rs.bold` with `rs.faint` and drop `rs.faint` altogether.

What terminal emulator are you using?

**Comment by clozach** [comment]
Sorry for the delayed response. Your workaround works, so thanks for that! In answer to your question, the above screenshot is the built-in Terminal.app on macOS Sierra (10.12.6).

**Comment by clozach** [comment]
No, faint works just fine. It's only rs.bold that seems to be broken:

![image](https://user-images.githubusercontent.com/124952/39225322-925039ca-4800-11e8-8d3e-bff26cd474c4.png)

I hope you don't have to drop `faint`…it's a nice style to have handy. :)

**Comment by feluxe** [comment]
Thanks for the feedback!

I did some more research on this and it looks like most terminals don't distinguish between resetters for bold and faint. They use a single sequence to reset both (bold and faint) at the same time. 

This means I have to merge `rs.bold` and `rs.faint` into something like `rs.bold_faint` and `rs.faint_bold`. The result would look a little bit ugly, e.g.: `ef.bold + "foo" + rs.bold_faint`, but I guess it's the only way.

**Comment by feluxe** [comment]
I published a new release including said changes. More about it in #4
