### ISSUE TITLE
Printing a Colour gives a Numeric Prefix instead of Coloured Text

### ISSUE THREAD

**Issue by JamesLovern** [feluxe/sty#34]
Hey there,

I'm trying to run the following line within my Py Project:
```py
print(fg(141) + 'HWID Check Failed! Please reset your bound HWID and try again!' + fg.rs)
```

However, upon execution, the following is printed to my Console:
```
←[38;5;141mHWID Check Failed! Please reset your bound HWID and try again!←[39m
```

I've tried running this within Git Bash inside of VSC, as well as in Powershell, but cannot get it to work. Would anyone happen to know why?
If you need any other information just reply and I'll be more than happy to reply!

Kind Regards,
James

**Comment by feluxe** [comment]
Hi, I think your problem might be related to: https://github.com/feluxe/sty/issues/2

Could you try with:

```python
import os

os.system("")

print(fg(141) + 'HWID Check Failed! Please reset your bound HWID and try again!' + fg.rs)
```
?

**Comment by JamesLovern** [comment]
Will give it a shot now!

**Comment by JamesLovern** [comment]
Yeah have a feeling it is a Windows only bug -- just tried to recreate on Macbook and seems to work fine! Will attempt fix in morning!

**Comment by JamesLovern** [comment]
Can confirm the fix does work! Thanks ever so much for your help!
