### ISSUE TITLE
Some RGB colors not supported?

### ISSUE THREAD

**Issue by alexpreynolds** [feluxe/sty#36]
As a test, I wrote a short script to take a DNA sequence and render a colored equivalent of it:

```
#!/usr/bin/env python

import sys
from sty import bg, rs

bg.orange = bg(255, 150, 50)

classic = {
    'G' : bg.orange,
    'T' : bg.red,
    'U' : bg.red,
    'C' : bg.blue,
    'A' : bg.green,
}

be = rs.bg

for line in sys.stdin:
    line = line.rstrip().upper()
    for char in line:
        if char in classic:
            sys.stdout.write(classic[char] + ' ' + be)
    sys.stdout.write('\n')
```

Entering a sample sequence into standard input that contains `G` will return blank characters with no background color (e.g., `ACGGAT`). Standard output contains blank characters with the expected background color for the non-G characters.

**Comment by feluxe** [comment]
Some terminals are not capable enough to support all features of sty. What OS and terminal are you using?

**Comment by alexpreynolds** [comment]
I am using Mac OS X 11.2.3 with Terminal emulating xterm-256color

**Comment by alexpreynolds** [comment]
There are shades of orange with rgb equivalents that this terminal type appears to support (such as `OrangeRed` and its rgb equivalent; ref. https://jonasjacek.github.io/colors/).

**Comment by feluxe** [comment]
I think the terminal.app in MacOS doesn't support RGB colors. It's already listed under [know issues](https://sty.mewo.dev/docs/known_issues.html#known-issues).

The color list from the link you posted shows the 8bit color palette. You can use 8bit colors like this, with sty:

```
my_string = fg(202) + "foo" + fg.rs
```

**Comment by alexpreynolds** [comment]
Thanks!
