### ISSUE TITLE
Background colors leak through to end of line on multilined text

### ISSUE THREAD

**Issue by daxxycodes** [feluxe/sty#45]
In Python on Mac OS 12 (zsh), while doing

`print(bg.blue + "some long line of text" + bg.rs)`

if "some long line of text" wraps to the next line in the terminal (say because the text hits the right edge of the terminal after "of"), then in the second line, the blank space after "text" will also be background-colored through to the right edge of the terminal window.

I can sorta fix it by doing

`print(bg.blue + "some long line of text" + bg.rs + "\033[0m\033[K")`

but it's unclear if this will work in all environments.

**Comment by feluxe** [comment]
Thanks for reporting this. Could you please send a screenshot?
