### ISSUE TITLE
More docstrings?

### ISSUE THREAD

**Issue by spenserblack** [feluxe/sty#46]
I often view documentation with `help(foo)`, possibly more often than viewing documentation on websites.
Currently `help(sty)` doesn't offer much info, and usage like `help(sty.ef)` will display the inherited docstring from the base `Register` class instead of describing what `ef` can do.

**Comment by feluxe** [comment]
Thanks for the suggestion. I just added doc strings to all modules and functions. It should be a lot better now.
If there's still something missing, please open another issue. Thanks!
