### ISSUE TITLE
SVG Logo

### ISSUE THREAD

**Issue by kubinka0505** [feluxe/sty#47]
I don't know why there's none. Add if you want. 🙂

---

| Default | [Aliased](https://stackoverflow.com/questions/23376308) |
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/30776937/198085405-9c11619d-62ad-4f4f-9737-a1f882ad254b.svg" width=170 alt="Default">|<img src="https://user-images.githubusercontent.com/30776937/198085408-3e9b4ef6-fa2c-4578-b933-4149c20e024f.svg" width=170>|

**Comment by feluxe** [comment]
@kubinka0505 Thanks, this is awesome! :heart: 
I'm really busy at the moment. I'll add them to the docs as soon as I can.

**Comment by feluxe** [comment]
Thanks again! It was added with the release today.
