### ISSUE TITLE
Program stops running

### ISSUE THREAD

**Issue by Jekaija** [feluxe/sty#48]
I installed sty (Python), and then, as in the instructions https://sty.mewo.dev/intro/getting_started.html, I did everything, it works!
I edited my .py file, of course, errors could (should) have appeared, as a result - the program is not executed, I need to edit it, here I return the original version of my file, and ... it no longer works.
The __pycache__ folder appears, some new file is in it, and nothing else works.
So what is this? How is this treated?

-----  myfile.py  -----
import os
os.system('color')
from sty import bg, ef, fg, rs
foo = fg.red + "red" + fg.rs
print(foo)
input("o")

**Comment by feluxe** [comment]
I'm sorry but I don't really understand what you want. The code you posted works on my machine.

![image](https://user-images.githubusercontent.com/6545589/205657521-ffe48b35-f1a0-44c8-9da4-55c5b28edf40.png)

**Comment by Jekaija** [comment]
The code works on my machine too. But it’s worth adding something to it and trying to execute it, as it no longer works. and it no longer works even if it is written in another folder.
myfile1.py
========
import os
os.system('color')
from sty import bg, ef, fg, rs
foo = fg.red + "red" + fg.rs
print(foo)
input("o")



myfile1.py   (аfter my edit, does not work)
========
import os
os.system('color')
from sty import bg, ef, fg, rs
foo = fg.red + "red" + fg.rs
print(foo)
# Add custom colors:
from sty import RgbFg, Style
fg.orange = Style(RgbFg(255, 150, 50))
buf = fg.orange + "Yay, Im orange." + fg.rs
print(buf)
input("o")

Why Python doesn't he want to work with such a simple code, because all the lines from the instructions?

Similar behavior is found for other programs installed in addition to existing ones, such as network ones. At first it works, then the same file is no longer executed.
