### ISSUE TITLE
Shortcuts module to easy use

### ISSUE THREAD

**Issue by vgavro** [feluxe/sty#8]
Hello. With string interpolation on Python3.6 it's really easy to use colors with print, but it may be even less verbose, even if it's much better than colorama in that way.
Maybe it will be good choice to support some shortcuts module?
For example, 
```python
import sty.shortcuts as f
print(f'Hello, {f.bred}hello{f.rs}')
```
f.bred = ef.b + fg.red
f.ured = ef.u + fg.red
f.ired = ef.i + fg.red,
f.rs = rs.all
f.xgreen = bg.green

I mean - I understand that we're talking about couple less symbols, but it would be very cool when you're hard working with colored output, plus - we have only one var in namespace.

**Comment by feluxe** [comment]
Thanks for your suggestion!

One of my goals for sty's api was to find a sweet spot between verbosity and obscurity. I wouldn't like to shorten the api any further. If I come across `f.bred`, `f.ured`, `f.ired`, `f.xgreen` in a code base (not knowing sty) I'd have a hard time figuring out what's going on. If I see `fg.red`, `bg.green` it's obvious, IMHO. That's a big trade-off for a couple symbols.

You would also need to add a resetter for each shortcut, unless you want to work with `rs.all` all the time.

I'm not convinced, that this is something I would like to have in sty. At least not for now.

**Comment by vgavro** [comment]
Thanks for feedback. I'll close issue then. Thanks for library!
